apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
spec:
  type: NodePort
  selector:
    app: my-node-app
  ports:
    - protocol: TCP
      port: 80         # External port exposed via the Service
      targetPort: 3000  # Internal port of your container
      nodePort: 30080   # The port on the node where the service will be exposed
